name: myits_sarprass
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Database
  supabase_flutter: ^2.10.3

  # --- DARI FITUR PROFILE ---
  image_picker: ^1.0.7          # Untuk ambil foto dari galeri/kamera
  shared_preferences: ^2.0.15   # Untuk simpan sesi login/data lokal
  path_provider: ^2.0.14        # Untuk akses direktori file sistem

  # --- DARI FITUR INFO & SEARCH ---
  url_launcher: ^6.2.5          # Untuk buka link browser/WA
  file_picker: ^8.0.0           # Untuk upload dokumen/file
  youtube_player_flutter: ^9.0.1 # Untuk putar video YouTube

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # --- KONFIGURASI ASET ---
  # Pastikan folder 'assets' dan 'images' sudah dibuat di dalam project
  assets:
    - assets/images/